# This file was generated by GoReleaser. DO NOT EDIT.
cask "float-mcp" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d86f70f06658b8ef78665f271a1d35600b435addaf59b73dc5d1b237ad90f2bc"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a52dc95750abab99594abda71b116de31e5b8b08e81786b69c5f06a84eb3bd9"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "99e3cb4febfcbb6e4637b2efb261a86c5d4842813307f1765c8306406e66d90e"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "87e5e34c38521e14687f0044b387671b7b9274ab430f44c73663483b5f9c8425"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "float-mcp"
  desc "Local stdio MCP server for Float time tracking"
  homepage "https://github.com/ericmann/float-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "float-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/float-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    float-mcp needs a Float API token to talk to Float:
      1. create a token:  Float → Team Settings → Integrations (account owner)
      2. provide it via the FLOAT_API_TOKEN env var, or
         ~/.config/float/config.json  ->  {"api_token": "..."}
      3. verify your setup:  float-mcp doctor

    Register it with your MCP client (e.g. Claude Code):
      claude mcp add float --env FLOAT_API_TOKEN=... -- float-mcp mcp
  EOS
end
