# This file was generated by GoReleaser. DO NOT EDIT.
cask "float-mcp" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "baba494cc406ced18e3fb17ab95adc9e59f418675bc0c369a9d987f98ab3f9e5"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38a1ca6a1a01baa3973a29794a4399716d5acb37e69180f9031e710c053cc1b9"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "96cb0c8b4b170660aa3c88de548e71c04abe60b2c51afe028305e5be9c296183"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ad552e736f1abbf3450312bf0a8bd9d31807ffb8481f16d47edc4997f4692d1"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "float-mcp"
  desc "Local stdio MCP server for Float time tracking"
  homepage "https://github.com/ericmann/float-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "float-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/float-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    float-mcp needs a Float API token to talk to Float:
      1. create a token:  Float → Team Settings → Integrations (account owner)
      2. provide it via the FLOAT_API_TOKEN env var, or
         ~/.config/float/config.json  ->  {"api_token": "..."}
      3. verify your setup:  float-mcp doctor

    Register it with your MCP client (e.g. Claude Code):
      claude mcp add float --env FLOAT_API_TOKEN=... -- float-mcp mcp
  EOS
end
