# This file was generated by GoReleaser. DO NOT EDIT.
cask "float-mcp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "745b1e13b4b0d5f80ec8bc1524ca1892318e7c70e0e18acb2612302842c28369"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e3a157d4bcc931a43f811a4ce0e2c626a72b8bb8830131ba877c52b78c1ec6f"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb9325f86cfefcb264ace81f15295dcd3c678eddaf6a4ecad5389e9c091a7924"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9004e01079b43cb025759df26658267b2516cde0900399282f5355989e589166"
      url "https://github.com/ericmann/float-mcp/releases/download/v#{version}/float-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "float-mcp"
  desc "Local stdio MCP server for Float time tracking"
  homepage "https://github.com/ericmann/float-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "float-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/float-mcp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    float-mcp needs a Float API token to talk to Float:
      1. create a token:  Float → Team Settings → Integrations (account owner)
      2. provide it via the FLOAT_API_TOKEN env var, or
         ~/.config/float/config.json  ->  {"api_token": "..."}
      3. verify your setup:  float-mcp doctor

    Register it with your MCP client (e.g. Claude Code):
      claude mcp add float --env FLOAT_API_TOKEN=... -- float-mcp mcp
  EOS
end
