# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "2.7.0"

  on_macos do
    on_intel do
      sha256 "f2968414fc6d35fb70eec45feed8c1a78671735bbb59216fd0508cfbdc7e44f1"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c544d54352b51042adba3775adb7785fc0e5b1211f8a603b9890aaeb09950585"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01ecef0b6a17beca15f18de9b3be7bafb5b8352f3f6241613364762e25524ed5"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c20bf9ba7c0805fc63a8bc53d7f58a050ae253fc5b19a74bed7bfef051cc2fe"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "journal"
  desc "Local-first developer journal with semantic search and AI synthesis"
  homepage "https://github.com/ericmann/journal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    journal needs a local Ollama for indexing and search:
      1. install Ollama:        https://ollama.com
      2. pull the embed model:  ollama pull qwen3-embedding:4b
      3. verify your setup:     journal doctor

    An ANTHROPIC_API_KEY in your environment is only needed for `journal synth`.
  EOS
end
