# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "2.4.2"

  on_macos do
    on_intel do
      sha256 "ce5a3cc3d7fa65b5384717ac5a4c30a1eebce4023fbf6ab07fa5c6c835b3bff1"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c92af842b28522073f574b7244697e18f27b4df931f0198e82395ea840af0b5f"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a8cb3493ad17685c120505e8e42a0f14fd4dfd648a7169bae7c51f30608babf"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "27537fb4c9dd3b3321e3ca6493c56f7d371e4e2d15532f529b6cdeb2b0146ae1"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "journal"
  desc "Local-first developer journal with semantic search and AI synthesis"
  homepage "https://github.com/ericmann/journal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    journal needs a local Ollama for indexing and search:
      1. install Ollama:        https://ollama.com
      2. pull the embed model:  ollama pull qwen3-embedding:4b
      3. verify your setup:     journal doctor

    An ANTHROPIC_API_KEY in your environment is only needed for `journal synth`.
  EOS
end
