# This file was generated by GoReleaser. DO NOT EDIT.
cask "journal" do
  version "2.6.1"

  on_macos do
    on_intel do
      sha256 "2236a768a4abbe22e0c62d0025053c32b68528797f3ec732d35f77c1346ec18a"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8031b6148d78097daf121889bdc7378b5482d7d270ff526b4ceee43b16cce3da"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e2264cba0fe372bdc1daa4c334266181a461702bf2d6096b55106739a9f6a90"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9dc443eaacd1efd09cd69396e1f101aedfb7aaa17e6e053cc8117e1b7a34ac1"
      url "https://github.com/ericmann/journal/releases/download/v#{version}/journal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "journal"
  desc "Local-first developer journal with semantic search and AI synthesis"
  homepage "https://github.com/ericmann/journal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "journal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/journal"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    journal needs a local Ollama for indexing and search:
      1. install Ollama:        https://ollama.com
      2. pull the embed model:  ollama pull qwen3-embedding:4b
      3. verify your setup:     journal doctor

    An ANTHROPIC_API_KEY in your environment is only needed for `journal synth`.
  EOS
end
